const { chromium } = require(process.env.POS_NODE_MODULES + '/playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  const context = await browser.newContext({viewport:{width:1024,height:768},hasTouch:true,acceptDownloads:true});
  const page = await context.newPage();
  const errors=[]; page.on('pageerror', e => errors.push(e.message));
  await page.goto('http://localhost:4173');
  await page.locator('[data-quantity="3"]').click();
  await page.locator('#next').click();
  assert.equal(await page.locator('.bill-total').innerText(),'¥900');
  assert.equal(await page.locator('#complete').isDisabled(),true);
  for(const k of '3000') await page.locator(`[data-key="${k}"]`).click();
  assert.equal(await page.locator('#change').innerText(),'¥2,100');
  await page.locator('#complete').evaluate(b=>{b.click();b.click();});
  await page.locator('[data-screen="history"]').click();
  await page.locator('tbody tr').first().waitFor(); assert.equal(await page.locator('tbody tr').count(),1);
  await page.locator('[data-screen="settings"]').click();
  for(const k of '350') await page.locator(`[data-key="${k}"]`).click();
  await page.locator('#save-price').click();
  await page.locator('[data-screen="quantity"]').click();
  await page.locator('[data-quantity="3"]').click(); await page.locator('#next').click();
  assert.equal(await page.locator('.bill-total').innerText(),'¥1,050');
  await page.locator('#skip').click();
  await page.locator('[data-screen="history"]').waitFor();
  await page.reload(); await page.locator('[data-screen="history"]').click();
  await page.locator('tbody tr').first().waitFor(); assert.equal(await page.locator('tbody tr').count(),2);
  assert.match(await page.locator('tbody').innerText(),/¥900/);
  await page.locator('[data-cancel]').first().click();
  await page.locator('#cancel-dialog button[value="close"]').click();
  assert.equal(await page.locator('.cancelled').count(),0);
  await page.locator('[data-cancel]').first().click(); await page.locator('#confirm-cancel').click();
  await page.locator('.cancelled').waitFor();
  assert.equal(await page.locator('.stats strong').first().innerText(),'¥900');
  const downloaded = page.waitForEvent('download'); await page.locator('#export-csv').click();
  const download=await downloaded; const downloadedPath=await download.path();
  assert.match(fs.readFileSync(downloadedPath,'utf8'),/350,3,1050,false/);
  await page.evaluate(()=>navigator.serviceWorker.ready);
  await context.setOffline(true); await page.reload();
  await page.locator('[data-quantity="1"]').click(); await page.locator('#next').click();
  assert.equal(await page.locator('.bill-total').innerText(),'¥350');
  await page.locator('#skip').click(); await page.locator('[data-screen="history"]').click();
  await page.locator('tbody tr').first().waitFor(); assert.equal(await page.locator('tbody tr').count(),3);
  await page.locator('[data-screen="quantity"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight),true);
  await page.screenshot({path:'tests/pos-preview.png',fullPage:true});
  // A real transaction abort must keep the current sale uncompleted and retryable.
  await page.locator('[data-quantity="2"]').click(); await page.locator('#next').click();
  await page.evaluate(()=>{window.realAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args){const request=window.realAdd.apply(this,args);this.transaction.abort();return request;};});
  await page.locator('#skip').click(); await page.locator('#message.error').waitFor();
  assert.equal(await page.locator('.bill-total').innerText(),'¥700');
  await page.evaluate(()=>{IDBObjectStore.prototype.add=window.realAdd;});
  await page.locator('#skip').click(); await page.locator('[data-screen="history"]').click();
  await page.locator('tbody tr').first().waitFor(); assert.equal(await page.locator('tbody tr').count(),4);
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: checkout, double click, price snapshot, reload, cancellation, CSV, offline sale, layout, aborted save and retry');
})().catch(e=>{console.error(e);process.exit(1);});

